# Generated by Django 3.2.7 on 2022-06-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SANITARYPRODUCTS', 'Sanitary Products'), ('BEAUTYPRODUCTS', 'Beauty Products'), ('HYGIENEPRODUCTS', 'Hygiene Products'), ('MEDICINES', 'Medicines'), ('VITAMINSKIDS', 'Vitamins Kids'), ('VITAMINSADULT', 'Vitamins Adult')], max_length=20),
        ),
    ]
