# Generated by Django 3.2.7 on 2022-06-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='addtiona_desciption',
            field=models.CharField(default=10, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='qauntity',
            field=models.IntegerField(default=10),
        ),
    ]
