# Generated by Django 3.2.7 on 2022-06-05 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220606_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
